### PR TITLE
Add default internet latency

### PR DESCRIPTION
**Pull request by perezp**
It was considered useful to have in the Optimizer a default value for the internet latency ( >0 ) in case that such value will not be configured

### CODE REVIEW

**Comment by rosogon** [comment]
Is it possible to have real latency values between data centers?

**Comment by perezp** [comment]
I don't know, but it would be wonderful to use real values. 

For what concerns this PR, this latency values are not "final", it's just a variable that can be set. 
At present, it is not being set; so it is better to have a default value of 200ms instead of a 0ms. 
It is not a final value anyway.

**Comment by kiuby88** [comment]
This PR looks good. can we merged it?

**Comment by perezp** [comment]
Thank you @kiuby88 . I'll merge it ASAP. I'm waiting until we have a clean master and we can execute travis before merging more PR.

**Pull request merged**
