### PR TITLE
Demo review integration and general structure provided

### PR DESCRIPTION
**Pull request by mbarrientos**
This integrates the work done on the Demo for the Review Meeting with the main structure of the platform. 
Several changes has been made:
- Added planner component (with optimizer skeleton included).
- Dashboard has been updated to the most recent state.
- Apache license headers are checked in every build.
- Author annotations have been removed.

### CODE REVIEW

**Comment by andreaturli** [comment]
@adriannieto please wait for the travis builder to report about the process

**Comment by andreaturli** [comment]
@mbarrientos 93 commits are really needed? I'm ok to merge it as-is, but next PR should contain 1 commit IMO

**Comment by andreaturli** [comment]
@adriannieto @mbarrientos @kiuby88 @javicubo I think it is ok to merge that, if you are happy as travis.

Next PRs must be more compact, as it is really hard to review a PR so complex that spawns so many areas in the project.

Just as an example, the current PR should have been at least 5 different PRs:
- Added planner component (with optimizer skeleton included).
- Dashboard has been updated to the most recent state.
- Apache license headers are checked in every build.
- Author annotations have been removed.
- Contributing guide provided.

BTW, where is the contributing guide?

**Comment by mbarrientos** [comment]
@andreaturli I completely agree with that. However, almost all of the commits have been reviewed in a separate branch, and there was not much work done at the master branch before.

The contributing guide can be found here: https://github.com/SeaCloudsEU/SeaCloudsPlatform/blob/master/CONTRIBUTING.md

**Comment by andreaturli** [comment]
Thanks @mbarrientos, I can't see any change on [CONTRIBUTING](https://github.com/SeaCloudsEU/SeaCloudsPlatform/blob/master/CONTRIBUTING.md) in this PR, as the description said.

**Comment by javicubo** [comment]
@andreaturli as @mbarrientos mentioned, although we know it is not the most appropriate way to do, it has been done like that to create the master without losing the previous (reviewed) commits.

**Comment by andreaturli** [comment]
@javicubo, it's ok. Just trying to set a common understanding so that we avoid that in the future.
Happy to merge it now, please ping Diego so that he can open its PR asap.

**Pull request merged**
