### PR TITLE
Several changes to match the new SeaClouds API.

### PR DESCRIPTION
**Pull request by adriannieto**
This includes some tweaks and improvements, among with a overall code clean-up on the JS side. This PR requires #221 to be merged in order to work properly.

### CODE REVIEW

**Comment by adriannieto** [comment]
I'm going to close this until I fix some issues found during the Jan 27th demo.

**Comment by adriannieto** [comment]
@andreaturli could you reopen this PR? I pushed force this branch and now it doesn't allow me to reopen  it

**Comment by andreaturli** [comment]
Cant do that as well

**Comment by adriannieto** [comment]
Dont worry I just opened another one. It seems that if you force push a closed PR GH loses the reference to the branch or sth like this.
El 29 ene. 2016 6:30 p. m., Andrea Turli <notifications@github.com> escribió:Cant do that as well

**Pull request closed without merging**
