### PR TITLE
fix planner maven structure

### PR DESCRIPTION
**Pull request by andreaturli**
uncomment optimizer
enable build for matchmaker and discoverer
fix maven layout for matchmaker,optimizer and discoverer
fix compilation errors (wtf!?)
fix parents in multiple pom.xml
remove unnecessary build plugins as inherited from parents
remove jdk8 requirement

### CODE REVIEW

**Comment by andreaturli** [comment]
Oh dear, what a mess!
This PR tries to fix what it looks more like a train wreck to me!

TODO
As the tosca-parser from a4c we need to remove the dependency on the old tosca-parser which is even coming from an external repository

**Comment by perezp** [comment]
Thank you for the PR!

Something new is happening in the tests of modules inside the planner, concretely in the optimizer. I do not see their outputs, although the report says that none of the tests failed. It happens in both my local machine and travis. It say this: 

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.998 sec

Results :

Tests run: 7, Failures: 0, Errors: 0, Skipped: 0

================================================================

I looked around for the solution. I found that adding the following dependency in the pom.xml , tests are shown again. 

<dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-simple</artifactId>
                <version>1.7.12</version>
</dependency>


Maybe it's not the proper solution. If it's a problem of the tests, let me know (the last time I checked the outputs from travis, tests were correctly shown without adding the previous dependency… I don't know). 
Please, @andreaturli let me also know if this is not even a matter of this PR but it's something that has to be dealt with in the next PR of the optimizer.

**Comment by perezp** [comment]
Thank you for the PR!

Something new is happening in the tests of modules inside the planner, concretely in the optimizer. I do not see their outputs, although the report says that none of the tests failed. It happens in both my local machine and travis. It say this:

T E S T S

Running TestSuite
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.998 sec

Results :

Tests run: 7, Failures: 0, Errors: 0, Skipped: 0

I looked around for the solution. I found that adding the following dependency in the pom.xml , tests are shown again.


`<dependency>`
`                <groupId>org.slf4j</groupId>`
 `               <artifactId>slf4j-simple</artifactId>`
`                <version>1.7.12</version>`
` </dependency>`

Maybe it's not the proper solution. If it's a problem of the tests, let me know (the last time I checked the outputs from travis, tests were correctly shown without adding the previous dependency… I don't know).
Please, @andreaturli let me also know if this is not even a matter of this PR but it's something that has to be dealt with in the next PR of the optimizer.

**Comment by andreaturli** [comment]
@perezp are you happy with it now? can we merge it?

**Comment by perezp** [comment]
@andreaturli Yes, I'm happy with it. 
 
Now all the version numbers are coherent. I had not merged it during these last days because I wanted to know if planner developers were also happy with the version number you chose  ``` 0.1.0-SNAPSHOT ```  for the planner module.

**Pull request merged**
