### PR TITLE
Optimizer

### PR DESCRIPTION
**Pull request by perezp**
Code of the SeaClouds optimizer for review . 
@andreaturli

### CODE REVIEW

**Comment by andreaturli** [comment]
@perezd Thanks for that. 47 commits is definitely too much for a single review: there is the risk that the PR touches too many areas. Anyway, I'll try to review them asap.

**Comment by andreaturli** [comment]
@perezp could you please at the reason travis is not happy?
I think it is related to the parent groupId in pom.xml

a couple of comments for the PR:
- remove commented code
- configure your IDE to have no tab indentation but 3 chars indent

Finally squash your 47 commits into 1 commit only named like "add initial optimizer implementation"
To do so, you can try by doing the following
```
# Switch to the master branch and make sure you are up to date.
git checkout master
git fetch # this may be necessary (depending on your git config) to receive updates on origin/master
git pull

# Merge the feature branch into the master branch.
git merge optimizer

# Reset the master branch to origin's state.
git reset origin/master

# Git now considers all changes as unstaged changes.
# We can add these changes as one commit.
# Adding . will also add untracked files.
git add --all
git commit
```
feel free to ping me on gitter if you need more help

**Comment by perezp** [comment]
@andreaturli I've completed all the steps in your comment.

Remaining doubts: 

- this was a PR of the optimizer branch, but after "git merge optimizer" the master branch in my fork was updated and I made the rest of changes in the master. If there is not an easy way to solve this, I can close this PR and start a new one from the master branch in my fork. 

- Regarding travis, I see the following error (I think it's the same error as in SeaCloudsEU): 

" [ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project platform: Failed to deploy artifacts: Could not transfer artifact eu.seaclouds-project:platform:pom:0.1.0-20150415.213941-4 from/to sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots/): Failed to transfer file: https://oss.sonatype.org/content/repositories/snapshots/eu/seaclouds-project/platform/0.1.0-SNAPSHOT/platform-0.1.0-20150415.213941-4.pom. Return code is: 401, ReasonPhrase: Unauthorized. -> [Help 1]
...
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
The command "mvn deploy --settings target/travis/settings.xml" exited with 1. 
"

**Comment by andreaturli** [comment]
thanks @perezp!

I think it is actually easier to close this PR and open a new one from your master.

I've seen the error from travis, I'll try to look at it later, don't bother too much

**Pull request closed without merging**
