### PR TITLE
Fix. Avoiding not-enable services will be able to be accessed.

### PR DESCRIPTION
**Pull request by kiuby88**

### CODE REVIEW

**Comment by rosogon** [comment]
Hi @kiuby88 . This PR is still valid, right? We have been testing it to deploy our case study and it works. It's +1 for me, even if it needs to be improved.

**Comment by kiuby88** [comment]
Yes @rosogon. It PR is necessary to deploy an application with bound services on CF, such as Atos use case.

**Comment by rosogon** [comment]
Ok, merging

**Comment by kiuby88** [comment]
Thx

**Pull request merged**
