### PR TITLE
Added a Api method to retrieve the location of all the SeaClouds Components

### PR DESCRIPTION
**Pull request by adriannieto**
@MicheleGuerriero  could you review this? This adds also the necessary method to retrieve where Grafana is deployed, so after the installation script become fixed it the dashboard will be wired properly.

### CODE REVIEW

**Comment by andreaturli** [comment]
@adriannieto this branch seems to have conflicts. Can you check it, please?

**Comment by adriannieto** [comment]
@andreaturli Since the installation method was upgrade, I'm checking if everything still works.

**Comment by adriannieto** [comment]
@andreaturli working now. The catalog currently has a fake graphite/graphana endpoint. I will have the proper one when @MicheleGuerriero  will find a fix for Graphite &  Grafana installation

**Comment by andreaturli** [comment]
@adriannieto lgtm

Could you please confirm that the seaclouds deployment is still working after this PR got merged?

**Pull request merged**
