### PR TITLE
(Feature)Planner: core and service update, matchmaker bugfix

### PR DESCRIPTION
**Pull request by szenzaro**
@rosogon can you review this please?

In order to test it be sure to have a running discoverer and sla-core and provide their urls to the planner configuration.

The PR fixes a bug in the matchmaker, provide an updated version of the dam generator with monitor and sla generators and improves DAM conformance.

@andreaturli: in order to be deployed the bom must be changed. Since you asked me to not update the bom, please contact me if you need help updating it.

### CODE REVIEW

**Comment by rosogon** [comment]
I get this exception with a wrong file. 

```
ERROR [2015-11-26 16:57:57,145] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 44034d5f71541468
! java.lang.NullPointerException: null
! at eu.seaclouds.platform.planner.service.PlanResource.getPlans(PlanResource.java:67) ~[planner-service-0.8.0-SNAPSHOT.jar:na]
! at eu.seaclouds.platform.planner.service.PlanResource.planPost(PlanResource.java:49) ~[planner-service-0.8.0-SNAPSHOT.jar:na]
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_31]
! at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_31]
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_31]
```

**Comment by rosogon** [comment]
Also failing with a (maybe) right TOSCA file. Please, try this:

`curl -X POST http://localhost:1234/planner/plan -d@"planner/aamwriter/src/main/resources/examples/web-chat_a am.yml"`

The exception (once avoid the NPE) is : 
```
ERROR [2015-11-26 17:16:58,956] eu.seaclouds.platform.planner.service.PlanResource: Context: null
Problem: mapping values are not allowed here
Note: null
Start: null
End  : null
! alien4cloud.tosca.parser.ParsingException: Context: null
! Problem: mapping values are not allowed here
! Note: null
! Start: null
! End  : null
! at alien4cloud.tosca.parser.YamlParser.parseFile(YamlParser.java:76) ~[planner-service-0.8.0-SNAPSHOT.jar:na]

! at alien4cloud.tosca.parser.YamlParser.parseFile(YamlParser.java:50) ~[planner-service-0.8.0-SNAPSHOT.jar:na]

! at alien4cloud.tosca.parser.YamlParser.parseFile(YamlParser.java:37) ~[planner-service-0.8.0-SNAPSHOT.jar:na]

! at eu.seaclouds.common.tosca.ToscaSerializer.fromTOSCA(ToscaSerializer.java:82) ~[planner-service-0.8.0-SNAPSHOT.jar:na]
! at eu.seaclouds.platform.planner.core.Planner.plan(Planner.java:150) ~[planner-service-0.8.0-SNAPSHOT.jar:na]
```

**Comment by szenzaro** [comment]
with [web-chat_aam.yml](https://github.com/SeaCloudsEU/SeaCloudsPlatform/blob/master/planner/aamwriter/src/main/resources/examples/web-chat_aam.yml) AAM i get [these ADPs](https://gist.github.com/szenzaro/f78ba61839c72b7fd993)

**Comment by andreaturli** [comment]
@szenzaro I think you have to change the seaclouds-planner item in the bom file. I asked you to not modify the applications inside the bom, that use the items.

It is really important that the PRs follow strictly our CONTRIBUTING guide. In particular, each developer MUST run 'mvn verify -pl qa -Pintegration' as unfortunately travis cannot do that reliably.
I think we should publish the result of that 'mvn verify' - maybe in the description of each PR - otherwise the PR will be *automatically* rejected. 

What do you think @kiuby88 @MicheleGuerriero @rosogon @adriannieto @PaoloCifariello @perezp?

**Comment by adriannieto** [comment]
I think it's a good way to be sure that everything is OK. 
By the way I'm going to enable health checks on  the dashboard, this means that if an endpoint is failing dropwizard will not start, but to achieve this I need to be sure that at least we get everything on green at deployment time.
El 27 nov. 2015 7:07 a. m., Andrea Turli <notifications@github.com> escribió:@szenzaro I think you have to change the seaclouds-planner item in the bom file. I asked you to not modify the applications inside the bom, that use the items.

It is really important that the PRs follow strictly our CONTRIBUTING guide. In particular, each developer MUST run 'mvn verify -pl qa -Pintegration' as unfortunately travis cannot do that reliably.
I think we should publish the result of that 'mvn verify' - maybe in the description of each PR - otherwise the PR will be automatically rejected. 

What do you think @kiuby88 @MicheleGuerriero @rosogon @adriannieto @PaoloCifariello @perezp?

**Comment by rosogon** [comment]
@szenzaro : You are right. My fault. That's why REST interfaces should log their inputs ;)

I'll test it again.

**Comment by rosogon** [comment]
Hi @szenzaro : I finally got the ADPs :)

Please, how do I test now the DAM Generation?

**Comment by szenzaro** [comment]
@rosogon POST /damgen with the ADP in body or GET /damgen with adp as query parameter

**Comment by rosogon** [comment]
+1: Generates ADPs and DAMs. I assume the DAM generation will need to be polished in a later PR. @szenzaro : please, squash into 1 commit.

**Comment by szenzaro** [comment]
@rosogon done. Thank you.

**Pull request merged**
