### PR TITLE
Feature/group management

### PR DESCRIPTION
**Pull request by kiuby88**
Groups are expected by Deployer as a topology_template's child.

### CODE REVIEW

**Comment by kiuby88** [comment]
@szenzaro @MicheleGuerriero  please take a look to this commit. Probably, we could expect groups as a topology_template's child.

**Comment by szenzaro** [comment]
+1 for me

**Comment by rosogon** [comment]
@kiuby88 : This branch has conflicts. Could you resolve this?

**Comment by kiuby88** [comment]
@rosogon sorry for the late response.
Rebased

**Comment by MicheleGuerriero** [comment]
I think this PR will make the monitoring-dam-generator-core module to not work since it changes the format of the input and my ADP parser will fail. If it is needed to be compliant with the TOSCA specification I can fix my parser, but I have some doubts this doesn't affect only me. @kiuby88 can you please help me in clarify how to handle this point?

**Comment by perezp** [comment]
@MicheleGuerriero We can talk on monday and I can make clear this change. I agree with you that this might not affect only you. 

I would keep the PR open until we solve these issues. 

@kiuby88

**Comment by andreaturli** [comment]
Stop using just Strings!

**Comment by andreaturli** [comment]
@kiuby88 please refactor 
```
public static String generateDam(String adp, String monitorGenURL, String monitorGenPort, String slaGenURL) {
```
into something Object Oriented like 
```
public DAM generateDAM(ADP adp) 
```
where ADP is probably just a4c's Topology and DAM is Topology + Policies, I think.

Do you think it is feasible?

**Comment by adriannieto** [comment]
@kiuby88 I'm doing something similar like @andreaturli proposes with SeaCloudsApplicationData.java (in https://github.com/adriannieto/SeaCloudsPlatform/blob/feature/move-orchestration-from-js-to-java/dashboard/src/main/java/eu/seaclouds/platform/dashboard/model/SeaCloudsApplicationData.java just in case you want to take a look), I agree with @andreaturli but @szenzaro must agree on this, because maybe it will involve a lot of changes.

**Comment by kiuby88** [comment]
@MicheleGuerriero , I did not know that your component used groups. I am sorry.
I have moved groups migration to `generateDam` method. 
Of course, it is a TEMPORAL solution.

**Comment by kiuby88** [comment]
I have solved issues 198 and 199 on this PR as a temporal solution. These issues should be fixed from AAM generation.

**Comment by kiuby88** [comment]
@szenzaro , could you take  a look?

**Comment by jacopogiallo** [comment]
We (UPI) agree on the updates by @kiuby88

**Comment by kiuby88** [comment]
Thanks a lot @jacopogiallo  and @andreaturli

**Pull request merged**
