### PR TITLE
Fix/travis build

### PR DESCRIPTION
**Pull request by andreaturli**

### CODE REVIEW

**Comment by andreaturli** [comment]
This fixes travis building PR, by reverting to the previous situation. Sorry for the inconvenience.

**Comment by rosogon** [comment]
@andreaturli , it it possible to make it work?. Although not working this time, it's still a good idea.

**Comment by andreaturli** [comment]
@rosogon not easy, it works only for PR coming from the SeacloudsPlatform branches but the idea was to deploy PR before merging them. Feel free to pick it up and improve it, if you like.

**Comment by andreaturli** [comment]
@rosogon See https://github.com/SeaCloudsEU/SeaCloudsPlatform/pull/156: I've changed slightly the approach to have the same automatic deployment intended before.

**Pull request merged**
