### PR TITLE
Requirements of a DataCollector node template ad now an array.

### PR DESCRIPTION
**Pull request by MicheleGuerriero**
This PR solves Issue #228 . @rosogon can you have a look?

### CODE REVIEW

**Comment by rosogon** [comment]
@MicheleGuerriero : It looks fine. Do you have an example of generated DAM?

**Comment by MicheleGuerriero** [comment]
@rosogon , yes I can attach the generated DAM for the current NURO dap. Should I put it in some folder or just paste it here?

**Comment by rosogon** [comment]
You can paste it here. Thanks

**Comment by MicheleGuerriero** [comment]
`tosca_definitions_version: tosca_simple_yaml_1_0_0_wd03
description: NURO application
imports: ['tosca-normative-types:1.0.0.wd06-SNAPSHOT']
topology_template:
  node_templates:
    php:
      type: sc_req.php
      properties:
        language: PHP
        location: ''
        autoscale: true
        php_version:
          constraints:
          - {greater_or_equal: '5.1'}
          - {less_or_equal: '5.5'}
        credentials_file: database.properties
      artifacts:
      - {file: 'https://<user>:<password>@seaclouds-dev.nurogames.com/nuro-casestudy/versions/current/nurogames-seaclouds-casestudy-php-current.tgz',
        type: tosca.artifacts.File}
      requirements:
      - {endpoint: database, type: seaclouds.relations.databaseconnections.php}
      - {host: OpenShift_Origin, instancesPOC: 2}
    database:
      type: sc_req.database
      properties:
        location: ''
        autoscale: false
        mysql_version:
          constraints:
          - {greater_or_equal: '5.1'}
          - {less_or_equal: '5.6'}
      artifacts:
      - {db_create: 'https://<user>:<password>@seaclouds-dev.nurogames.com/nuro-casestudy/versions/current/create_db_and_tables-current.sql',
        type: tosca.artifacts.File}
      requirements:
      - {host: OpenShift_Origin, instancesPOC: 1}
    OpenShift_Origin:
      type: seaclouds.nodes.Compute.OpenShift_Origin
      properties: {postgresql_support: true, php_version: 5.5, auto_scaling: true,
        jboss_support: true, postgresql_version: 9.2, horizontal_scaling: true, python_version: 3.3,
        vertical_scaling: true, jboss_version: 8.0, php_support: true, node_support: true,
        tomcat_version: 7, private_hosting: true, mongodb_version: 2.4, resource_type: platform,
        node_version: 0.1, ruby_version: 2.0, tomcat_support: true, mongodb_support: true,
        public_hosting: false, mysql_version: 5.5, java_support: true, python_support: true,
        ruby_support: true, java_version: 7, mysql_support: true, performance: 80,
        availability: 0.99825, cost: 0.02}
    modacloudsDc_php:
      requirements:
      - {host: OpenShift_Origin}
      interfaces:
        Standard: {start: 'https://s3-eu-west-1.amazonaws.com/modacloudsdc-start-script/installModacloudsDc.sh'}
      type: seaclouds.nodes.Datacollector
      properties:
        install.latch: $brooklyn:component("php").attributeWhenReady("service.isUp")
        shell.env: {MODACLOUDS_TOWER4CLOUDS_MANAGER_PORT: '8170', MODACLOUDS_TOWER4CLOUDS_RESOURCES_KEEP_ALIVE_PERIOD: '25',
          MODACLOUDS_TOWER4CLOUDS_INTERNAL_COMPONENT_ID: php_ID, MODACLOUDS_TOWER4CLOUDS_INFLUXDB_IP: 52.48.12.68,
          MODACLOUDS_TOWER4CLOUDS_INFLUXDB_PORT: '8083', MODACLOUDS_TOWER4CLOUDS_INTERNAL_COMPONENT_TYPE: php,
          MODACLOUDS_TOWER4CLOUDS_VM_TYPE: OpenShift_Origin, MODACLOUDS_TOWER4CLOUDS_DC_SYNC_PERIOD: '10',
          MODACLOUDS_TOWER4CLOUDS_MANAGER_IP: 52.48.12.68, MODACLOUDS_TOWER4CLOUDS_VM_ID: OpenShift_Origin_ID}
node_types:
  sc_req.php:
    derived_from: seaclouds.nodes.ControlledDynamicWebAppCluster
    properties:
      php_support:
        constraints:
        - {equal: true}
      php_version:
        constraints:
        - {greater_or_equal: '5.1'}
        - {less_or_equal: '5.5'}
  sc_req.database:
    derived_from: seaclouds.nodes.database.mysql.MySqlNode
    properties:
      mysql_support:
        constraints:
        - {equal: true}
      mysql_version:
        constraints:
        - {greater_or_equal: '5.1'}
        - {less_or_equal: '5.6'}
  seaclouds.nodes.Compute:
    derived_from: tosca.nodes.Compute
    description: Custom compute
    properties:
      hardwareId: {required: false, type: string}
  seaclouds.nodes.Datacollector: |
    derived_from: tosca.nodes.Root
    description: >
     A simple Tomcat server
    properties:
     install_latch:
      type: string
      required: false
     shell.env:
      type: map
      required: false
      entry_schema:
       type: string
    requirements:
     - host: tosca.nodes.Compute
       type: tosca.relationships.HostedOn
groups:
  operation_php:
    members: [php]
    policies:
    - QoSInfo: {execution_time: 4 ms, benchmark_platform: Amazon_EC2_m1_large_us_east_1}
    - dependencies: {operation_database: '1'}
    - AppQoSRequirements:
        response_time: {less_than: 2000.0 ms}
        availability: {greater_than: 0.99}
        cost: {less_or_equal: 800.0 euros_per_month}
        workload: {less_or_equal: 50.0 req_per_min}
    - QoSRequirements:
        AverageResponseTime: {less_than: 2000.0 ms}
    - ExpectedQualityPOC: {expectedAvailabilityPOC: 0.998246942859375, fitnessPOC: 44.22283914119642,
        expectedCostPOC: 43.199999999999996, expectedExecutionTimePOC: 0.008829267782962082}
    - autoscaling: {maxPoolSize: 55, metric: '$brooklyn:sensor(\"seaclouds.nodes.ControlledDynamicWebAppCluster\",
          \"webapp.reqs.perSec.windowed.perNode\")', minPoolSize: 1, metricUpperBound: 72.05208333333333,
        type: seaclouds.policies.autoscalling.AutoscalerPolicy, metricLowerBound: 36.026041666666664}
  operation_database:
    members: [database]
    policies:
    - QoSInfo: {execution_time: 15 ms, benchmark_platform: Amazon_EC2_m1_large_us_east_1}
    - dependencies: {}
    - QoSRequirements:
        AverageResponseTime: {less_than: 2000.0 ms}`

This is the output from the monitoring-dam-generator updated to this PR.

**Comment by MicheleGuerriero** [comment]
tosca_definitions_version: tosca_simple_yaml_1_0_0_wd03
description: NURO application
imports: ['tosca-normative-types:1.0.0.wd06-SNAPSHOT']
topology_template:
  node_templates:
    php:
      type: sc_req.php
      properties:
        language: PHP
        location: ''
        autoscale: true
        php_version:
          constraints:
          - {greater_or_equal: '5.1'}
          - {less_or_equal: '5.5'}
        credentials_file: database.properties
      artifacts:
      - {file: 'https://<user>:<password>@seaclouds-dev.nurogames.com/nuro-casestudy/versions/current/nurogames-seaclouds-casestudy-php-current.tgz',
        type: tosca.artifacts.File}
      requirements:
      - {endpoint: database, type: seaclouds.relations.databaseconnections.php}
      - {host: OpenShift_Origin, instancesPOC: 2}
    database:
      type: sc_req.database
      properties:
        location: ''
        autoscale: false
        mysql_version:
          constraints:
          - {greater_or_equal: '5.1'}
          - {less_or_equal: '5.6'}
      artifacts:
      - {db_create: 'https://<user>:<password>@seaclouds-dev.nurogames.com/nuro-casestudy/versions/current/create_db_and_tables-current.sql',
        type: tosca.artifacts.File}
      requirements:
      - {host: OpenShift_Origin, instancesPOC: 1}
    OpenShift_Origin:
      type: seaclouds.nodes.Compute.OpenShift_Origin
      properties: {postgresql_support: true, php_version: 5.5, auto_scaling: true,
        jboss_support: true, postgresql_version: 9.2, horizontal_scaling: true, python_version: 3.3,
        vertical_scaling: true, jboss_version: 8.0, php_support: true, node_support: true,
        tomcat_version: 7, private_hosting: true, mongodb_version: 2.4, resource_type: platform,
        node_version: 0.1, ruby_version: 2.0, tomcat_support: true, mongodb_support: true,
        public_hosting: false, mysql_version: 5.5, java_support: true, python_support: true,
        ruby_support: true, java_version: 7, mysql_support: true, performance: 80,
        availability: 0.99825, cost: 0.02}
    modacloudsDc_php:
      requirements:
      - {host: OpenShift_Origin}
      interfaces:
        Standard: {start: 'https://s3-eu-west-1.amazonaws.com/modacloudsdc-start-script/installModacloudsDc.sh'}
      type: seaclouds.nodes.Datacollector
      properties:
        install.latch: $brooklyn:component("php").attributeWhenReady("service.isUp")
        shell.env: {MODACLOUDS_TOWER4CLOUDS_MANAGER_PORT: '8170', MODACLOUDS_TOWER4CLOUDS_RESOURCES_KEEP_ALIVE_PERIOD: '25',
          MODACLOUDS_TOWER4CLOUDS_INTERNAL_COMPONENT_ID: php_ID, MODACLOUDS_TOWER4CLOUDS_INFLUXDB_IP: 52.48.12.68,
          MODACLOUDS_TOWER4CLOUDS_INFLUXDB_PORT: '8083', MODACLOUDS_TOWER4CLOUDS_INTERNAL_COMPONENT_TYPE: php,
          MODACLOUDS_TOWER4CLOUDS_VM_TYPE: OpenShift_Origin, MODACLOUDS_TOWER4CLOUDS_DC_SYNC_PERIOD: '10',
          MODACLOUDS_TOWER4CLOUDS_MANAGER_IP: 52.48.12.68, MODACLOUDS_TOWER4CLOUDS_VM_ID: OpenShift_Origin_ID}
node_types:
  sc_req.php:
    derived_from: seaclouds.nodes.ControlledDynamicWebAppCluster
    properties:
      php_support:
        constraints:
        - {equal: true}
      php_version:
        constraints:
        - {greater_or_equal: '5.1'}
        - {less_or_equal: '5.5'}
  sc_req.database:
    derived_from: seaclouds.nodes.database.mysql.MySqlNode
    properties:
      mysql_support:
        constraints:
        - {equal: true}
      mysql_version:
        constraints:
        - {greater_or_equal: '5.1'}
        - {less_or_equal: '5.6'}
  seaclouds.nodes.Compute:
    derived_from: tosca.nodes.Compute
    description: Custom compute
    properties:
      hardwareId: {required: false, type: string}
  seaclouds.nodes.Datacollector: |
    derived_from: tosca.nodes.Root
    description: >
     A simple Tomcat server
    properties:
     install_latch:
      type: string
      required: false
     shell.env:
      type: map
      required: false
      entry_schema:
       type: string
    requirements:
     - host: tosca.nodes.Compute
       type: tosca.relationships.HostedOn
groups:
  operation_php:
    members: [php]
    policies:
    - QoSInfo: {execution_time: 4 ms, benchmark_platform: Amazon_EC2_m1_large_us_east_1}
    - dependencies: {operation_database: '1'}
    - AppQoSRequirements:
        response_time: {less_than: 2000.0 ms}
        availability: {greater_than: 0.99}
        cost: {less_or_equal: 800.0 euros_per_month}
        workload: {less_or_equal: 50.0 req_per_min}
    - QoSRequirements:
        AverageResponseTime: {less_than: 2000.0 ms}
    - ExpectedQualityPOC: {expectedAvailabilityPOC: 0.998246942859375, fitnessPOC: 44.22283914119642,
        expectedCostPOC: 43.199999999999996, expectedExecutionTimePOC: 0.008829267782962082}
    - autoscaling: {maxPoolSize: 55, metric: '$brooklyn:sensor(\"seaclouds.nodes.ControlledDynamicWebAppCluster\",
          \"webapp.reqs.perSec.windowed.perNode\")', minPoolSize: 1, metricUpperBound: 72.05208333333333,
        type: seaclouds.policies.autoscalling.AutoscalerPolicy, metricLowerBound: 36.026041666666664}
  operation_database:
    members: [database]
    policies:
    - QoSInfo: {execution_time: 15 ms, benchmark_platform: Amazon_EC2_m1_large_us_east_1}
    - dependencies: {}
    - QoSRequirements:
        AverageResponseTime: {less_than: 2000.0 ms}

**Comment by MicheleGuerriero** [comment]
You can have a look at it here http://pastebin.com/gu49F2XP .

**Comment by rosogon** [comment]
+1. Merging

**Comment by rosogon** [comment]
Closes #228

**Pull request merged**
