### PR TITLE
FIX: create autoscaler policy with agnostic information

### PR DESCRIPTION
**Pull request by perezp**
Changed the optimizer code to create policies with the structure as in the following example: 
```
 policies:
      - autoscaling:
          type: seaclouds.policies.autoscaling.AutoScalerPolicy
          metric: seaclouds.metrics.requestPerNode
          autoscaler.resizeDownStabilizationDelay: 120000
          metricLowerBound: N1
          metricUpperBound: N2
          minPoolSize: N3
          maxPoolSize: N4
```

### CODE REVIEW

**Comment by kiuby88** [comment]
@perezp , thanks a lot for this.
Could you provide an example of a generated ADP with policy?

**Comment by perezp** [comment]
@kiuby88 
Here it is an example of ADP for an input AAM of a three-tier app www+ws+db
https://gist.github.com/perezp/704d148cb2e65b3c2fff

**Comment by kiuby88** [comment]
:+1:  merge!!!!!!!!

**Comment by perezp** [comment]
Thank you @kiuby88

**Pull request merged**
