### PR TITLE
FIX(dashboard): Nodes behaviour was lost when going back to step 2

### PR DESCRIPTION
**Pull request by rosogon**

### CODE REVIEW

**Comment by rosogon** [comment]
Hi, @perezp. ¿Could you have a look at why this PR is failing?

**Comment by adriannieto** [comment]
Thank you @rosogon nice catch. It seems that you fixed partially this annoying bug, however it looks that only the edit button is working, because when you back to the step 2 from the step 3, you can't delete nodes. Could you take a look?

**Comment by perezp** [comment]
@rosogon Done. 
External service hosting the optimizer that is requested in some tests was not active. 
I'll remove this test to avoid more problems of this type in the future.

**Comment by adriannieto** [comment]
@rosogon Please do the following, goto step 2, add a node, go to step 3, back to step 2 remove a node, add a node. You can't remove this one. Could you check it?

**Comment by adriannieto** [comment]
Nice, now it works! Just squash it before merge. +1

**Comment by rosogon** [comment]
Squashed. Merging

**Pull request merged**
