### PR TITLE
Features/deployer types mapping

### PR DESCRIPTION
**Pull request by kiuby88**
Adding DeployerTypeResolver to DamGenerator. A mapping was added to describe the relation between SeaClouds Types and Deployer (Brooklyn) types.
This will be useful for adding PaaS support because the ssh types and paas types will depend on target location.

### CODE REVIEW

**Comment by kiuby88** [comment]
@szenzaro could you take a look please?

**Comment by kiuby88** [comment]
@szenzaro could you take a look again please??

**Comment by kiuby88** [comment]
@szenzaro, could you take a look please?
thx

**Comment by kiuby88** [comment]
@szenzaro I have added some new features, could you take a look again?
Thanks a lot

**Comment by szenzaro** [comment]
+1 for me

**Comment by kiuby88** [comment]
We should refactor the generator in order to add more test

**Comment by kiuby88** [comment]
So it could be merged, right?

**Pull request merged**
