### PR TITLE
FIX(sla): Removed unused spring-security dependencies

### PR DESCRIPTION
**Pull request by rosogon**
This fixes issue #90, due to the use of a higher spring version in SeacloudsPlatform than the one used in sla development.

### CODE REVIEW

**Comment by perezp** [comment]
Thanks @rosogon 

+1 
Besides the changes in sla/sla-core/sla-service/pom.xml, you are removing also dependencies in pom.xml. Nobody else is affected by this? If you are sure of it, I don't have any other comment.

**Comment by rosogon** [comment]
Hi @perezp . There is no dependency to spring-security in the rest of the projects, so nobody is using it.

**Comment by perezp** [comment]
So, for me it is fine if you merge it. Also travis is fine with the PR.

**Comment by rosogon** [comment]
I will rebase and merge.

**Pull request merged**
