### PR TITLE
start brooklyn server on travis VM

### PR DESCRIPTION
**Pull request by andreaturli**
- deploy seaclouds on localhost
- re-enable -Ptravis profile
- fix permissions on brooklyn.properties
- add automatic deployment of the entire SeaClouds platform using just built artifacts

### CODE REVIEW

**Comment by szenzaro** [comment]
@andreaturli the [updated catalog](https://github.com/szenzaro/SeaCloudsPlatform/blob/feature/plannerCatalogUpdate/seaclouds-catalog.bom) may solve the issue. Cloud you please help me understand why brooklyn does not accept it throwing null pointer exception?

**Comment by andreaturli** [comment]
@adriannieto can you have a look at it?
it seems that the build is failing because the maven-grunt-plugin is failing to reach to github.com

https://travis-ci.org/SeaCloudsEU/SeaCloudsPlatform/builds/92068194#L1198

Any ideas? Do you think using `maven-frontend-plugin` can solve this issue as well as the problem reported by @MicheleGuerriero ?

Thanks

**Comment by adriannieto** [comment]
@andreaturli hum, it seems that the maven plugin has nothing to do here. Bower is failing to retrieve the dependencies:

```
bower components-font-awesome#~4.4.0     ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/components/font-awesome.git", exit code of #128 fatal: unable to connect to github.com: github.com[0: 192.30.252.128]: errno=Connection timed out
```

Maybe we could configure Travis to retry the build if it fails.

**Comment by andreaturli** [comment]
I'm not able to do that and I'm not convinced it is the right thing to do.

**Comment by adriannieto** [comment]
@andreaturli the point is bower step will be required with independence of the plugin we use. If we don't run this step the dashboard will not have any dependency.

**Comment by andreaturli** [comment]
Sorry @adriannieto maybe I was not clear. The dashboard is failing on our CI server, do you think you can fix it?

**Comment by adriannieto** [comment]
@andreaturli it seems that it's also failing for @MicheleGuerriero he just notified me about this issue. GitHub is changing the website but status view is saying that there is no issues.

First time
```
bower angular#~1.4.7                        ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/angular/bower-angular.git", exit code of #128 fatal: unable to connect to github.com: github.com[0: 192.30.252.131]: errno=Connection timed out
```

Second time
```
bower Chart.js#~1.0.2                    ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/nnnick/Chart.js.git", exit code of #128 fatal: unable to connect to github.com: github.com[0: 192.30.252.130]: errno=Connection timed out
```

Third time
```
bower jquery#~2.1.4                      ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/jquery/jquery.git", exit code of #128 fatal: unable to connect to github.com: github.com[0: 192.30.252.128]: errno=Connection timed out
```


What do you think?

**Comment by andreaturli** [comment]
I don't know, ubi maior ...

Anyway travis previously compiled this PR on my fork https://travis-ci.org/andreaturli/SeaCloudsPlatform/builds/92068181 and looked fine.

I'm happy to merge it and revert it again, if things go sideways. wdyt?

**Comment by adriannieto** [comment]
I agree, it looks like a GH issue.

**Pull request closed without merging**
