### PR TITLE
Adds specification of frontend node in the designer.

### PR DESCRIPTION
**Pull request by rosogon**
A frontend node is specified in the topology as a boolean property in
the properties of a node. Visually, it appears with black rounded line.
The rest of nodes appears with a grey rounded line. Only one frontend
node can be specified.

This way of specifying a frontend has less priority than the previous
one when generating the AAM (setting the frontend node in the
app_requirements element), but it is easier to implement from the designer.

Form code for the topology editor has been moved from editor.js to
editor-forms.js, as the former file was too complex.

### CODE REVIEW

**Comment by rosogon** [comment]
@kiuby88 , @jacopogiallo : Could you have a look at this? I can provide a working instance so you can test UI side.

**Comment by jacopogiallo** [comment]
@rosogon Looking to the code, and according to your comment, it seems that only the UI has changed. The generated AAM is still the same. Isn't it?

(And yes, a running instance - or at least two screenshots highlighting differences - would be great) :)

**Comment by rosogon** [comment]
@jacopogiallo : I will privately give you the instance url. The important change is in the UI. A little change has been done in the aamwriter, since I modified the specification of the frontend node in the topology json.

**Comment by rosogon** [comment]
@jacopogiallo : A node form contain now a checkbox to mark the node as frontend. The node marked as frontend is rounded in black while the others are rounded in grey.

**Comment by jacopogiallo** [comment]
>  I will privately give you the instance url. 
Fine, I tried it. (It is not generating ADPs since, I guess, the instance you gave me is not connected to the Planner - isn't it?) 
>The important change is in the UI. A little change has been done in the aamwriter, since I modified the specification of the frontend node in the topology json.
I understand this. Is the AAM you generate going to be different from the previous ones? I am asking to be sure that the small changes you are committing will not affect the entire design time. :)

> A node form contain now a checkbox to mark the node as frontend. The node marked as frontend is rounded in black while the others are rounded in grey.
I see. Would it be possible to highlight it in a more effective way? Perhaps it could be even another color (blue? green? since black is not so differrent from dark-grey).

**Comment by rosogon** [comment]
@jacopogiallo: I haven't checked, but I think it is connected to the planner.
The AAM has not changed.

I am afraid the color is a question of taste. I will ask the demo for any agreement on this.

**Comment by jacopogiallo** [comment]
@rosogon 

>I haven't checked, but I think it is connected to the planner.
The AAM has not changed.

Could you please make a quick check? I mean, can you check that the Planner is connected and that the AAM you generate can still be used to generate ADPs (and then DAMs)?

>I am afraid the color is a question of taste. I will ask the demo for any agreement on this.

I agree, of course. It was just a suggestion. ;)

**Comment by rosogon** [comment]
@jacopogiallo, could you test now if you are able to get results from the planner? Thanks

**Comment by jacopogiallo** [comment]
@rosogon Sorry but I cannot review it before coming monday. If you need it earlier, could you please explain the issue to @PaoloCifariello (or anybody else) and ask him to do the review?

**Comment by jacopogiallo** [comment]
@rosogon I saw the screenshot you sent me on Gitter. If it is generating DAMs properly, it is fine with me :) 

If you still need a light review, please ask it to somebody else (e.g., @PaoloCifariello )

**Comment by perezp** [comment]
@rosogon  I've tested the GUI and the PR does what it claims. 
+1

**Comment by rosogon** [comment]
Squashed and merged. Thanks @perezp

**Pull request merged**
