### PR TITLE
FEATURE: Added ADP autogeneration to the wizard.

### PR DESCRIPTION
**Pull request by adriannieto**
This will add the wizard the capability to autogenerate the ADP from Step 1 and 2.

### CODE REVIEW

**Comment by adriannieto** [comment]
@rosogon  could you review this?

**Comment by rosogon** [comment]
The code is ok to me. I'm testing the PR right now.

**Comment by adriannieto** [comment]
@rosogon let me know when it's ready to merge in order to squash everything.

**Comment by rosogon** [comment]
@adriannieto : Tested locally and on byon deployment. +1. Please squash to merge.

**Pull request merged**
