### PR TITLE
FIX(Dashboard): fixed wrong artifact bug

### PR DESCRIPTION
**Pull request by mbarrientos**
Fixed bug where dashboard brooklyn entity was downloading the wrong artifact. 
Also setting default values for config keys.

### CODE REVIEW

**Comment by mbarrientos** [comment]
@rosogon @MicheleGuerriero @perezp Could any of you guys have a look? Thanks!

**Comment by rosogon** [comment]
@mbarrientos : I don't understand the purpose of this file. Does it "receive" the values specified in the blueprint and set default values if not set in the blueprint?

**Comment by mbarrientos** [comment]
@rosogon Thanks for the review. 

The config keys default values are only used if there's nothing specified in the blueprint. In the way that the dashboard is built right now, all configuration values are mandatory so having default values gives a bit more consistency on built.

**Comment by rosogon** [comment]
+1

**Comment by perezp** [comment]
+1

**Pull request merged**
