### PR TITLE
First Version of SeaClouds Object Model interface

### PR DESCRIPTION
**Pull request by szenzaro**
Maybe @andreaturli and @adriannieto can look at this?

### CODE REVIEW

**Comment by adriannieto** [comment]
You accidentally included two commits that don't belong to your PR. Please perform a rebase before we review your work (Otherwise it's a little bit tricky to identify your contribution)

**Comment by szenzaro** [comment]
Is it fixed now?

**Comment by adriannieto** [comment]
No, it's still showing three commits (two from Andrea and one from yourself). Could you show us the status of your current tree? I realized that you're working on your master branch, you should work in different branches for each feature. 

Please read the contributing guide (https://github.com/SeaCloudsEU/SeaCloudsPlatform/blob/master/CONTRIBUTING.md) in order to avoid this kind of problems.

Thank you!

**Comment by szenzaro** [comment]
I close this. I created a new PR following the guidelines.

**Pull request closed without merging**
