### PR TITLE
Docs/Fix(Planner), Docs(Discoverer)

### PR DESCRIPTION
**Pull request by PaoloCifariello**
- Updated Planner configuration file with "cloudfoundry-istance" artifact
- Updated Planner README with all configuration variables
- Updated Discoverer README with mongoimport as requirement
- Fixed DAM Generator issue, now Monitoring rules are correctly passed to SLA 

@rosogon, @jacopogiallo can you please review it?

### CODE REVIEW

**Comment by kiuby88** [comment]
@PaoloCifariello, could you rebase it? #294 contains an useful feature to test this PR

**Comment by jacopogiallo** [comment]
No comments from my side. +1

**Comment by rosogon** [comment]
Regarding AgreementGenerator, it would be good to have a unit test using mockserver.

**Comment by kiuby88** [comment]
This PR is included in #297. Then, it should be closed.

**Pull request merged**
