### PR TITLE
Updating Normative Types version that is used by AAM

### PR DESCRIPTION
**Pull request by kiuby88**

### CODE REVIEW

**Comment by andreaturli** [comment]
Thanks @kiuby88 
do we need to update also the version used by a4c's ToscaParser ?

**Comment by kiuby88** [comment]
Thanks for your reply, @andreaturli.
It is not necessary. a4c's ToscaParser is already using this version.
But `tosca-normative-types:1.0.0.wd03-SNAPSHOT` is present in a lot of file still.

**Comment by andreaturli** [comment]
thanks @kiuby88

**Comment by kiuby88** [comment]
Thx @andreaturli

**Pull request merged**
