### PR TITLE
Moved SeaClouds entities to shared module "common".

### PR DESCRIPTION
**Pull request by mbarrientos**

### CODE REVIEW

**Comment by adriannieto** [comment]
How this affects to the usage of the platform? Does the usage guide need some changes?

**Comment by mbarrientos** [comment]
@adriannieto The installer shouldn't change. The moved entities are brought back to the installer as a maven dependency.

**Comment by andreaturli** [comment]
@mbarrientos the refactoring looks good *but* it breaks the `*.yaml` files in `usage/installer`.

Either they need to reference the new `dashboard.yaml` or update serviceType to something like `eu.seaclouds.common.entities.dashboard.SeaCloudsDashboard`

**Comment by mbarrientos** [comment]
Thanks @andreaturli for catching that. It should be fine now.

**Comment by andreaturli** [comment]
@mbarrientos the deployment looks better now
I can see this on the logs

```
2015-06-15 13:45:51,921 WARN  Installation of Java 1.7 failed at SeacloudsDashboardImpl{id=sv22yKcD}@SshMachineLocation[SshMachineLocation:ld2O:192.168.100.10/192.168.100.10:22@ld2OxGqG]: E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
WARNING: no known/successful package manager to install {apt=openjdk-7-jdk, yum=java-1.7.0-openjdk-devel}, may fail subsequently

2015-06-15 13:45:57,926 WARN  SSH task ended with exit code 1 when non-zero was not explicitly allowed (error may be thrown in future), in Task[ssh: install java (1.7):qB3CkKb0]: install java (1.7)
2015-06-15 13:45:57,927 WARN  Installation of Java 1.7 failed at TomcatServerImpl{id=jU8tVCa1}@SshMachineLocation[SshMachineLocation:ld2O:192.168.100.10/192.168.100.10:22@ld2OxGqG]: E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
WARNING: no known/successful package manager to install {apt=openjdk-7-jdk, yum=java-1.7.0-openjdk-devel}, may fail subsequently
```
and then
```
2015-06-15 14:00:09,262 WARN  Error invoking start at SeacloudsDashboardImpl{id=sv22yKcD}: Software process entity SeacloudsDashboardImpl{id=sv22yKcD} did not pass is-running check within the required 2m limit (2m 3s elapsed)
```

Could you please make sure that the installer keeps working as expected after this PR? Thanks

**Comment by mbarrientos** [comment]
@andreaturli not sure, but it looks like `sla-core` is blocking `apt-get` lock on the same machine. Is this any known issue in brooklyn?

**Comment by andreaturli** [comment]
@mbarrientos not sure about the problem. Two hints: 
- is `seaclouds.yaml` working? this would mean that it is a problem on byon only
- I'd try with `install.latch` on sla-core until `sla-db` is running just for the byon yaml

**Comment by adriannieto** [comment]
@andreaturli @mbarrientos this is the same problem i faced on Pisa. I think it's related with byon, maybe trying to deploy seaclouds platform to amazon could help to find the issue.

The temporary workaround is to preinstall libaio1 (in order to allow Mysql to run), openjdk-7-jdk (in order to fix the version mismatch, as sla requires Java 7 but the Tomcat entity installs Java 6) and unzip (in order to let the datacollectors to be installed)

**Comment by adriannieto** [comment]
I think this must be closed by #81 wdty @mbarrientos  @andreaturli ?

**Comment by mbarrientos** [comment]
@adriannieto Right, this is overriden on #81, so closing already.

**Pull request closed without merging**
