### PR TITLE
fix seaclouds-on-byon

### PR DESCRIPTION
**Pull request by andreaturli**
@rosogon could you review it?

### CODE REVIEW

**Comment by rosogon** [comment]
Thanks, @andreaturli . I'll try asap.

**Comment by andreaturli** [comment]
with `curl http://sla-core:sla-port/seaclouds/config`
I get back
```
SLA_URL=http://192.168.100.11:8080
METRICS_URL=http://192.168.100.10:8170/v1/metrics
```
is it correct?

**Comment by rosogon** [comment]
It's the right behaviour if sla is deployed in 8080.

**Comment by andreaturli** [comment]
Ok good, I can merge it if you like

**Comment by rosogon** [comment]
Hi @andreaturli . I confirm it also works for me. +1

**Pull request merged**
