### PR TITLE
Discoverer (Core)

### PR DESCRIPTION
**Pull request by buccarel**
All the functionalities of the core layer have been added.
Furthermore, it is possible to manually feed the local repository with a POST request or starting at the url of the add_offer servlet.

### CODE REVIEW

**Comment by buccarel** [comment]
@andreaturli @szenzaro The PR for the discoverer core and rest layer is ready. Travis seems to have some issues related to the Matchmaker and the Optimizer. I don't really know why, since on my computer everything compiled successfully. Can you two please review my PR?
Thanks.

**Comment by szenzaro** [comment]
Before accepting the PR I'd suggest to squash the commits into a single one and to fix the problem.
The PR contains deleted files for the SOM and the matchmaker. Be sure to PR only your changes to the discoverer. 
Change the title of the PR following the guide at https://github.com/SeaCloudsEU/SeaCloudsPlatform/blob/master/CONTRIBUTING.md

After these steps we can code review the PR.

**Comment by buccarel** [comment]
Ok, it turned out that I made the wrong PR, starting from the wrong code that I had before.
It is possible to cancel this one so I can PR again the right code please?
Thanks.

**Comment by adriannieto** [comment]
@buccarel just as a tip, as long as you remain on the same branch, you can modify the PR without the need of closing and opening a new one.

**Comment by buccarel** [comment]
@adriannieto I discovered that I did the wrong PR, wrong branch, wrong code. Also, I accidentally closed the PR myself.... I am sorry for this.
I will make the right PR soon. Thanks.

**Pull request closed without merging**
