### PR TITLE
Feature/remove installer

### PR DESCRIPTION
**Pull request by andreaturli**
- remove `usage/installer`
- update READE.md
- provide `seaclouds-catalog.bom` that can be used from plain Apache Brookyn to deploy `seaclouds-on-byon` or `seaclouds` on the clouds

@kiuby88 could you please test it?

### CODE REVIEW

**Comment by rosogon** [comment]
I think we are not using setup.sh anymore, so it can be removed.

**Comment by andreaturli** [comment]
ok @rosogon, removed

**Comment by rosogon** [comment]
Hi @andreaturli : I'm not able to launch brooklyn according to the instructions.

```
>bin\brooklyn.bat --catalogAdd \cygwin64\tmp\SeaCloudsPlatform\seaclouds-catalog.bom
Parse error: Found unexpected parameters: [--catalogAdd, \cygwin64\tmp\SeaCloudsPlatform\seaclouds-catalog.bom]


usage: brooklyn [(-v | --verbose)] [(-q | --quiet)] <command> [<args>]

The most commonly used brooklyn commands are:
    cloud-blobstore     Access blobstore details of a given cloud
    cloud-compute       Access compute details of a given cloud
    copy-state          Retrieves persisted state
    generate-password   Generates a hashed web-console password
    help                Display help for available commands
    info                Display information about brooklyn
    launch              Starts a server, optionally with applications
    list-objects        List Brooklyn objects (Entities, Policies, Enrichers and Locations)

See 'brooklyn help <command>' for more information on a specific command.
```

**Comment by andreaturli** [comment]
@rosogon, can you see if the README.md is more understandable, please?

**Comment by rosogon** [comment]
I share my experience in Windows :(

It looks like at some point, brooklyn changes CWD to %BROOKLYN_HOME%, and when starting, cannot find ..\seaclouds-catalog.bom. You must use absolute path. The same happens with the path of the private key (you must use absolute path).

If it at least works right in *nix, +1.

**Comment by andreaturli** [comment]
thanks @rosogon I've added some notes for Win users.

I think @kiuby88 is testing this PR as well, waiting for his feedback before merging.

**Comment by rosogon** [comment]
Besides the problem with paths, I confirm all components are deployed.

**Comment by rosogon** [comment]
@andreaturli : @szenzaro points out that we should add the blueprint for the discoverer (in #104).

It can be added here or in another PR. Wdyt?

**Comment by andreaturli** [comment]
@rosogon: leave #104 open for now. I'll re-use the yaml blueprint in there, to modify the `seaclouds-catalog.pom`

**Comment by rosogon** [comment]
Discoverer deploys and works. +1

**Comment by kiuby88** [comment]
+1

**Comment by andreaturli** [comment]
thanks @rosogon and @kiuby88, merging now

**Pull request merged**
